export const CART_ADD_ITERM = "CART_ADD_ITERM";
export const CART_REMOVE_ITERM = "CART_REMOVE_ITERM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_EMPTY = "CART_EMPTY";
